name: "Unmind Infrastructure Composite Action :: AWS Assume Role"
description: "Assumes role in another account"
inputs:
  account-id:
    description: "Account number"
    required: true
  aws-region:
    description: "The AWS region"
    required: true
    default: "eu-west-1"
  role-name:
    description: "Role name"
    required: true
  role-duration-seconds:
    description: "Role duration seconds"
    required: true
    default: 900
  role-session-name:
    description: "Role session name"
    required: true
    default: "IamPermsGHASync"
  
runs:
  using: "composite"
  steps:  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{inputs.aws-region}}
        role-to-assume: arn:aws:iam::${{inputs.account-id}}:role/${{inputs.role-name}}
        role-duration-seconds: ${{ inputs.role-duration-seconds }}
        role-session-name: ${{ inputs.role-session-name }}
